#include <stdio.h>
#include "pico/stdlib.h"
#include "hardware/gpio.h"
#include "hardware/pwm.h"


// include mis propios .h
#include "motor_control.h" // .h definicion de variables y metodos para el control del motor
#include "bluetooth.h" // .h definicion de todo lo relacionado a la comunicación bluetooth
#include "sharedfunctions.h" // es el que comparte funciones con el codigo bluetooth.c

void initPWM(uint8_t gpio, uint16_t frec){
    uint slice = pwm_gpio_to_slice_num(gpio);  // Get the value of the slice the gpio belongs to
    uint channel = pwm_gpio_to_channel(gpio);  // Get the value of the CHANNEL (A or B) to wich the gpio belongs in the specific slice.
    assert(frec>=8);                                             ///< PWM can manage interrupt periods greater than 262 milis - 3.5Hz-> see on sdk
    float prescaler = (float)SYS_CLK_KHZ/500;
    assert(prescaler<256); ///< the integer part of the clock divider can be greater than 255. 8bit prescaler
    uint32_t wrap = (500000)/(frec); // if mode phase_correct is actived,it means that the frecuency is divided by 2.
    assert(wrap<((1UL<<16)-1)); // validate wrap less than 16bits -> max is 65536
    pwm_config cfg =  pwm_get_default_config();
    //pwm_config_set_phase_correct(&cfg,true);   // the correct phase mode signal is defined. true
    pwm_config_set_clkdiv(&cfg,prescaler);     // split clock system running at 125MHz to run slower
    pwm_config_set_clkdiv_mode(&cfg,PWM_DIV_FREE_RUNNING);  // mode PMW_DIV_FREE_RUNNING, counts always up to wrap value. no need input b
    pwm_config_set_wrap(&cfg,wrap);   // set the wrap value, calculated based on frecuency of reloj system and frecuency required.
    //pwm_set_irq_enabled(slice,true);  // Enable PWM instance interrupt, each slice need to enabled the pwm irq when is used
    //irq_set_enabled(PWM_IRQ_WRAP,true); //Enable or disable a specific interrupt on the executing core. The same Interrupt is generated by all slices    
    pwm_init(slice,&cfg,true);  // Enables the slice pwm. when the bool value is true.
}


void initMotor(uint8_t PWM_GPIO){
    gpio_set_function(PWM_GPIO, GPIO_FUNC_PWM);// enable GPIO like PMW function.
    pwm_set_chan_level(pwm_gpio_to_slice_num(PWM_GPIO), pwm_gpio_to_channel( PWM_GPIO), 800); // set duty cycle of pwm signal, its choose based on Wrap config
    sleep_ms(3000); 
    pwm_set_chan_level(pwm_gpio_to_slice_num(PWM_GPIO), pwm_gpio_to_channel(PWM_GPIO), 750); 
}

void moverMotor(char* buffer){
    printf("Command: %s\n", buffer);
 
}




int main(){
    stdio_init_all();
    // initialize all pwm channel and slice depend of motors pin selected.

    /*
    initPWM(PWM_GPIO_MOTOR_ONE , FRECUENCY_ALL_PWM_MOTORS);
    if(pwm_gpio_to_slice_num(PWM_GPIO_MOTOR_ONE)!= pwm_gpio_to_slice_num(PWM_GPIO_MOTOR_TWO)){
        initPWM(PWM_GPIO_MOTOR_TWO , FRECUENCY_ALL_PWM_MOTORS);
    }
    initPWM(PWM_GPIO_MOTOR_THREE , FRECUENCY_ALL_PWM_MOTORS);
    if(pwm_gpio_to_slice_num(PWM_GPIO_MOTOR_ONE)!= pwm_gpio_to_slice_num(PWM_GPIO_MOTOR_TWO)){
        initPWM(PWM_GPIO_MOTOR_FOUR , FRECUENCY_ALL_PWM_MOTORS);
    }

    //All motors are initialized one by one. Takes 2 seconds per motor
    initMotor(PWM_GPIO_MOTOR_ONE);
    initMotor(PWM_GPIO_MOTOR_TWO);
    initMotor(PWM_GPIO_MOTOR_THREE);
    initMotor(PWM_GPIO_MOTOR_FOUR);
    */

    //Init comunication 
    initUart(GPIO_UART_TX, GPIO_UART_RX);


    printf("End of configuration");
    sleep_ms(1000);
    int duty = 750;
    int flag = 5;
    while (1) {

        printf("Alive");
        if(flag==1){
            // pwm_set_gpio_level(PWM_GPIO_MOTOR_ONE, duty);
            // pwm_set_gpio_level(PWM_GPIO_MOTOR_TWO, duty);
            // pwm_set_gpio_level(PWM_GPIO_MOTOR_THREE, duty);
            // pwm_set_gpio_level(PWM_GPIO_MOTOR_FOUR, duty);
            flag = 0;
        }

        duty = 750;
        sleep_ms(1000);

    /*
        pwm_set_gpio_level(PWM_GPIO_MOTOR_ONE, duty);
        pwm_set_gpio_level(PWM_GPIO_MOTOR_TWO, duty);
        pwm_set_gpio_level(PWM_GPIO_MOTOR_THREE, duty);
        pwm_set_gpio_level(PWM_GPIO_MOTOR_FOUR, duty);

       

        if(flag == 0){
            duty =  680;
            sleep_ms(5000);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_ONE, duty);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_TWO, duty);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_THREE, duty);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_FOUR, duty);
            flag = 2;
        }
        */




        /*
    
        while(duty < 1000){
            duty +=10;
            pwm_set_gpio_level(PWM_GPIO_MOTOR_ONE, duty);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_TWO, duty);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_THREE, duty);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_FOUR, duty);
            sleep_ms(1000);
        }

        while(duty>750){
            duty -=10;
            pwm_set_gpio_level(PWM_GPIO_MOTOR_ONE, duty);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_TWO, duty);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_THREE, duty);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_FOUR, duty);
            sleep_ms(1000);
        }

        while(duty>500){
            duty-=10;
            pwm_set_gpio_level(PWM_GPIO_MOTOR_ONE, duty);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_TWO, duty);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_THREE, duty);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_FOUR, duty);
            sleep_ms(1000);
        }

        while(duty<750){
            duty+=10; 
            pwm_set_gpio_level(PWM_GPIO_MOTOR_ONE, duty);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_TWO, duty);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_THREE, duty);
            pwm_set_gpio_level(PWM_GPIO_MOTOR_FOUR, duty);
            sleep_ms(1000);
        }

        sleep_ms(3000);
        */
     }
}
    

